### ISSUE TITLE
Setup time violations every few seconds

### ISSUE THREAD

**Issue by BigEd** [hoglet67/PiTubeDirect#2] opened 2016-10-17 05:47 UTC
Running the Sphere benchmark, with the lib6502 model on a Pi Zero, we notice screen corruptions once per minute or so. (With a logic analyser triggering on the nTube signal we didn't see setup violations, which was puzzling.)

Using a logic analyser with a more precise trigger and running a Basic loop
```
REPEAT A=PI/2.5: UNTIL 0
```
we see a setup time violation (for host reads) every few seconds.

We see that there are far fewer setup violations running Elite on the 65tubeasm model, but they still occur.

There are fewer or less serious violations running the gpu branch, compared to the ARM ISR in the main branch.

**Comment by hoglet67** [comment] 2016-10-18 09:07
The root cause of this was attempting a memory access in the critical section of the GPU polling loop where 6502 reads are dealt with. Switching to using I/O space has entirely fixed the issue. Fixed in GPU branch in 8cddf7bfed161b2e8eef147dc12460c8f4868a92

**Closed by hoglet67** 2016-10-18 09:07 UTC
